<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PilihNilaiSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ["id"=>1,"nomer"=>1,"nilai"=>0,"desc"=>"0 : belum ada SKI"],
            ["id"=>2,"nomer"=>1,"nilai"=>1,"desc"=>"1 : ada SKI dan ditetapkan dengan SK"],
            ["id"=>3,"nomer"=>2,"nilai"=>0,"desc"=>"0 : belum ada mekanisme pemilihan anggota SKI"],
            ["id"=>4,"nomer"=>2,"nilai"=>1,"desc"=>"1 : ada mekanisme pemilihan anggota SKI"],
            ["id"=>5,"nomer"=>3,"nilai"=>0,"desc"=>"0 : Tidak ada ketua SKI dan atau mekanisme penunjukan ketua SKI"],
            ["id"=>6,"nomer"=>3,"nilai"=>0.5,"desc"=>"0,5 : Ada ketua SKI namun tidak ditunjuk melalui mekanisme yang jelas"],
            ["id"=>7,"nomer"=>3,"nilai"=>1,"desc"=>"1 : ada Ketua SKI yang telah dipilih melalui mekanisme yang jelas"],
            ["id"=>8,"nomer"=>4,"nilai"=>0,"desc"=>"0 : belum ada personil SKI yang mengikuti pelatihan tata kelola organisasi (good governance)"],
            ["id"=>9,"nomer"=>4,"nilai"=>0.5,"desc"=>"0,5 : sebagian personil SKI sudah mengikuti pelatihan tata kelola organisasi (good governance)"],
            ["id"=>10,"nomer"=>4,"nilai"=>1,"desc"=>"1 : seluruh personil SKI sudah mengikuti pelatihan tata kelola organisasi (good governance)"],
            ["id"=>11,"nomer"=>5,"nilai"=>0,"desc"=>"0 : belum ada personil SKI yang mengikuti pelatihan manajemen risiko"],
            ["id"=>12,"nomer"=>5,"nilai"=>0.5,"desc"=>"0,5 : sebagian personil SKI sudah mengikuti pelatihan manajemen risiko"],
            ["id"=>13,"nomer"=>5,"nilai"=>1,"desc"=>"1 : seluruh personil SKI sudah mengikuti pelatihan manajemen risiko"],
            ["id"=>14,"nomer"=>6,"nilai"=>0,"desc"=>"0 : belum ada personil SKI yang mengikuti pelatihan SPIP"],
            ["id"=>15,"nomer"=>6,"nilai"=>0.5,"desc"=>"0,5 : sebagian personil SKI sudah mengikuti pelatihan SPIP"],
            ["id"=>16,"nomer"=>6,"nilai"=>1,"desc"=>"1 : seluruh personil SKI sudah mengikuti pelatihan SPIP"],
            ["id"=>17,"nomer"=>7,"nilai"=>0,"desc"=>"0 : belum ada program pengembangan SDM"],
            ["id"=>18,"nomer"=>7,"nilai"=>0.5,"desc"=>"0,5 : ada progam pengembangan SDM dan sebagian sudah terlaksana"],
            ["id"=>19,"nomer"=>7,"nilai"=>1,"desc"=>"1 : ada progam pengembangan SDM, sudah terlaksana dan dilakukan evaluasi berkelanjutan"],
            ["id"=>20,"nomer"=>8,"nilai"=>0,"desc"=>"0 : belum ada kebijakan internal"],
            ["id"=>21,"nomer"=>8,"nilai"=>0.5,"desc"=>"0,5 : ada kebijakan internal namun belum mengatur dengan jelas kebebasan akses data/informasi serta kewajiban pihak internal untuk memberikan data/informasi kepada SKI"],
            ["id"=>22,"nomer"=>8,"nilai"=>1,"desc"=>"1 : ada kebijakan internal yang mengatur dengan jelas kebebasan akses data/informasi serta kewajiban pihak internal untuk memberikan data/informasi kepada SKI"],
            ["id"=>23,"nomer"=>9,"nilai"=>0,"desc"=>"0 : sulit memperoleh data/informasi"],
            ["id"=>24,"nomer"=>9,"nilai"=>1,"desc"=>"1 : Mudah memperoleh data/informasi"],
            ["id"=>25,"nomer"=>10,"nilai"=>0,"desc"=>"0 : belum memanfaatkan data/informasi untuk perbaikan GRC"],
            ["id"=>26,"nomer"=>10,"nilai"=>0.5,"desc"=>"0,5 : belum seluruh data/informasi di manfaatkan untuk perbaikan GRC"],
            ["id"=>27,"nomer"=>10,"nilai"=>1,"desc"=>"1 : sudah memanfaatkan keseluruhan data/informasi yang diperoleh untuk perbaikan GRC"],
            ["id"=>28,"nomer"=>11,"nilai"=>0,"desc"=>"0 : belum ada prosedur"],
            ["id"=>29,"nomer"=>11,"nilai"=>1,"desc"=>"1 : ada prosedur"],
            ["id"=>30,"nomer"=>12,"nilai"=>0,"desc"=>"0 : belum berpartisipasi"],
            ["id"=>31,"nomer"=>12,"nilai"=>0.5,"desc"=>"0,5 : kadang berpartisipasi"],
            ["id"=>32,"nomer"=>12,"nilai"=>1,"desc"=>"1 : sudah berpartisipasi secara aktif"],
            ["id"=>33,"nomer"=>13,"nilai"=>0,"desc"=>"0 : belum menyampaikan laporan tepat waktu"],
            ["id"=>34,"nomer"=>13,"nilai"=>0.5,"desc"=>"0,5 : sudah menyampaikan laporan namun belum tepat waktu"],
            ["id"=>35,"nomer"=>13,"nilai"=>1,"desc"=>"1 : laporan sudah disampaikan secara rutin dan tepat waktu"],
            ["id"=>36,"nomer"=>14,"nilai"=>0,"desc"=>"0 : tidak ada upaya untuk meningkatkan mutu penyelenggaraan pemerintahan yang baik"],
            ["id"=>37,"nomer"=>14,"nilai"=>0.5,"desc"=>"0,5 : upaya untuk meningkatkan mutu penyelenggaraan pemerintahan yang baik masih bersifat parsial"],
            ["id"=>38,"nomer"=>14,"nilai"=>1,"desc"=>"1 : terdapat upaya yang sistematis dan berkelanjutan untuk meningkatkan mutu penyelenggaraan pemerintahan yang baik"],
            ["id"=>39,"nomer"=>15,"nilai"=>0,"desc"=>"0 : belum ada komunikasi aktif antar unit kerja untuk mendukung pelaksanaan GRC"],
            ["id"=>40,"nomer"=>15,"nilai"=>0.5,"desc"=>"0,5 : sudah ada komunikasi namun belum rutin dan terdokumentasi dengan baik"],
            ["id"=>41,"nomer"=>15,"nilai"=>1,"desc"=>"1 : sudah ada komunikasi rutin, terdokumentasi, dan mendukung kolaborasi antar unit kerja untuk pelaksanaan GRC"],
            ["id"=>42,"nomer"=>16,"nilai"=>0,"desc"=>"0 : belum ada evaluasi dan tindak lanjut hasil pengawasan"],
            ["id"=>43,"nomer"=>16,"nilai"=>0.5,"desc"=>"0,5 : ada evaluasi namun belum lengkap dan tidak semua ditindaklanjuti"],
            ["id"=>44,"nomer"=>16,"nilai"=>1,"desc"=>"1 : ada evaluasi rutin dan seluruh hasil pengawasan ditindaklanjuti"],
            ["id"=>45,"nomer"=>17,"nilai"=>0,"desc"=>"0 : tidak ada pelaporan tindak lanjut hasil pengawasan kepada pimpinan"],
            ["id"=>46,"nomer"=>17,"nilai"=>1,"desc"=>"1 : ada pelaporan hasil pengawasan dan tindak lanjut kepada pimpinan secara rutin"],
            ["id"=>47,"nomer"=>18,"nilai"=>0,"desc"=>"0 : tidak ada pelibatan pimpinan dalam proses pengawasan dan pengambilan keputusan GRC"],
            ["id"=>48,"nomer"=>18,"nilai"=>1,"desc"=>"1 : pimpinan terlibat aktif dalam proses pengawasan dan pengambilan keputusan GRC"],
            ["id"=>49,"nomer"=>19,"nilai"=>0,"desc"=>"0 : belum menggunakan teknologi informasi untuk mendukung implementasi GRC"],
            ["id"=>50,"nomer"=>19,"nilai"=>1,"desc"=>"1 : telah memanfaatkan teknologi informasi dalam mendukung implementasi GRC"],
            ["id"=>51,"nomer"=>20,"nilai"=>0,"desc"=>"0 : belum ada SOP tertulis dalam pelaksanaan GRC"],
            ["id"=>52,"nomer"=>20,"nilai"=>1,"desc"=>"1 : sudah ada SOP tertulis dalam pelaksanaan GRC"],
            ["id"=>53,"nomer"=>21,"nilai"=>0,"desc"=>"0 : belum dilakukan evaluasi terhadap efektivitas pelaksanaan GRC"],
            ["id"=>54,"nomer"=>21,"nilai"=>1,"desc"=>"1 : sudah dilakukan evaluasi terhadap efektivitas pelaksanaan GRC dan digunakan untuk perbaikan berkelanjutan"],
            ["id"=>55,"nomer"=>22,"nilai"=>0,"desc"=>"0 : belum ada pemahaman terhadap prinsip GRC di seluruh jenjang organisasi"],
            ["id"=>56,"nomer"=>22,"nilai"=>1,"desc"=>"1 : pemahaman prinsip GRC telah merata di seluruh jenjang organisasi"],
            ["id"=>57,"nomer"=>23,"nilai"=>0,"desc"=>"0 : belum ada forum koordinasi pelaksanaan GRC"],
            ["id"=>58,"nomer"=>23,"nilai"=>1,"desc"=>"1 : terdapat forum koordinasi pelaksanaan GRC secara berkala"],
            ["id"=>59,"nomer"=>24,"nilai"=>0,"desc"=>"0 : belum ada mekanisme pelaporan pelaksanaan GRC"],
            ["id"=>60,"nomer"=>24,"nilai"=>1,"desc"=>"1 : telah ada mekanisme pelaporan pelaksanaan GRC secara terstruktur dan rutin"],
            ["id"=>61,"nomer"=>25,"nilai"=>0,"desc"=>"0 : belum ada kebijakan manajemen risiko"],
            ["id"=>62,"nomer"=>25,"nilai"=>1,"desc"=>"1 : telah ditetapkan kebijakan manajemen risiko yang menjadi dasar dalam penerapan GRC"],
            ["id"=>63,"nomer"=>26,"nilai"=>0,"desc"=>"0 : belum dilakukan identifikasi risiko"],
            ["id"=>64,"nomer"=>26,"nilai"=>1,"desc"=>"1 : telah dilakukan identifikasi risiko utama organisasi"],
            ["id"=>65,"nomer"=>27,"nilai"=>0,"desc"=>"0 : belum ada analisis risiko"],
            ["id"=>66,"nomer"=>27,"nilai"=>1,"desc"=>"1 : telah dilakukan analisis terhadap risiko utama organisasi"],
            ["id"=>67,"nomer"=>28,"nilai"=>0,"desc"=>"0 : belum dilakukan pemetaan risiko"],
            ["id"=>68,"nomer"=>28,"nilai"=>1,"desc"=>"1 : telah dilakukan pemetaan risiko dan disusun peta risiko organisasi"],
            ["id"=>69,"nomer"=>29,"nilai"=>0,"desc"=>"0 : belum ada rencana tindak pengendalian risiko"],
            ["id"=>70,"nomer"=>29,"nilai"=>1,"desc"=>"1 : telah disusun rencana tindak pengendalian risiko"],
            ["id"=>71,"nomer"=>30,"nilai"=>0,"desc"=>"0 : belum ada proses pemantauan risiko"],
            ["id"=>72,"nomer"=>30,"nilai"=>1,"desc"=>"1 : telah dilakukan proses pemantauan risiko secara berkala"],
            ["id"=>73,"nomer"=>31,"nilai"=>0,"desc"=>"0 : belum ada pelaporan risiko kepada pimpinan"],
            ["id"=>74,"nomer"=>31,"nilai"=>1,"desc"=>"1 : telah ada pelaporan risiko secara berkala kepada pimpinan"],
            ["id"=>75,"nomer"=>32,"nilai"=>0,"desc"=>"0 : belum ada keterlibatan pimpinan dalam pengelolaan risiko"],
            ["id"=>76,"nomer"=>32,"nilai"=>1,"desc"=>"1 : pimpinan terlibat aktif dalam pengelolaan risiko"],
            ["id"=>77,"nomer"=>33,"nilai"=>0,"desc"=>"0 : belum ada komunikasi risiko di seluruh tingkatan organisasi"],
            ["id"=>78,"nomer"=>33,"nilai"=>1,"desc"=>"1 : telah dilakukan komunikasi risiko di seluruh tingkatan organisasi"],
            ["id"=>79,"nomer"=>34,"nilai"=>0,"desc"=>"0 : belum ada budaya sadar risiko"],
            ["id"=>80,"nomer"=>34,"nilai"=>1,"desc"=>"1 : telah dibangun budaya sadar risiko dalam organisasi"],
            ["id"=>81,"nomer"=>35,"nilai"=>0,"desc"=>"0 : belum ada struktur organisasi yang mendukung pelaksanaan GRC"],
            ["id"=>82,"nomer"=>35,"nilai"=>1,"desc"=>"1 : telah ada struktur organisasi yang mendukung pelaksanaan GRC"],
            ["id"=>83,"nomer"=>36,"nilai"=>0,"desc"=>"0 : belum ada dokumen strategi implementasi GRC"],
            ["id"=>84,"nomer"=>36,"nilai"=>1,"desc"=>"1 : telah disusun dokumen strategi implementasi GRC"],
            ["id"=>85,"nomer"=>37,"nilai"=>0,"desc"=>"0 : belum ada indikator kinerja pengelolaan risiko"],
            ["id"=>86,"nomer"=>37,"nilai"=>1,"desc"=>"1 : telah ditetapkan indikator kinerja pengelolaan risiko"],
            ["id"=>87,"nomer"=>38,"nilai"=>0,"desc"=>"0 : belum ada evaluasi pelaksanaan manajemen risiko"],
            ["id"=>88,"nomer"=>38,"nilai"=>1,"desc"=>"1 : telah dilakukan evaluasi pelaksanaan manajemen risiko"],
            ["id"=>89,"nomer"=>39,"nilai"=>0,"desc"=>"0 : belum ada pelaporan hasil pengelolaan risiko"],
            ["id"=>90,"nomer"=>39,"nilai"=>1,"desc"=>"1 : telah ada pelaporan hasil pengelolaan risiko kepada pimpinan"],
            ["id"=>91,"nomer"=>40,"nilai"=>0,"desc"=>"0 : belum ada pelibatan pemangku kepentingan dalam pengelolaan risiko"],
            ["id"=>92,"nomer"=>40,"nilai"=>1,"desc"=>"1 : telah melibatkan pemangku kepentingan dalam pengelolaan risiko"],
            ["id"=>93,"nomer"=>41,"nilai"=>0,"desc"=>"0 : belum ada kebijakan pengendalian intern"],
            ["id"=>94,"nomer"=>41,"nilai"=>1,"desc"=>"1 : telah ada kebijakan pengendalian intern"],
            ["id"=>95,"nomer"=>42,"nilai"=>0,"desc"=>"0 : belum ada kegiatan pengendalian intern"],
            ["id"=>96,"nomer"=>42,"nilai"=>1,"desc"=>"1 : telah dilakukan kegiatan pengendalian intern secara berkala"],
            ["id"=>97,"nomer"=>43,"nilai"=>0,"desc"=>"0 : belum ada pemantauan atas pengendalian intern"], ["id"=>98,"nomer"=>43,"nilai"=>1,"desc"=>"1 : telah dilakukan pemantauan atas pengendalian intern"],
            ["id"=>99,"nomer"=>44,"nilai"=>0,"desc"=>"0 : belum ada pelaporan hasil pengendalian intern"],
            ["id"=>100,"nomer"=>44,"nilai"=>1,"desc"=>"1 : telah ada pelaporan hasil pengendalian intern secara berkala"],
            ["id"=>101,"nomer"=>45,"nilai"=>0,"desc"=>"0 : belum ada pengembangan sistem informasi untuk mendukung GRC"],
            ["id"=>102,"nomer"=>45,"nilai"=>1,"desc"=>"1 : telah dilakukan pengembangan sistem informasi untuk mendukung GRC"],
            ["id"=>103,"nomer"=>46,"nilai"=>0,"desc"=>"0 : belum ada pelatihan GRC yang terencana"],
            ["id"=>104,"nomer"=>46,"nilai"=>1,"desc"=>"1 : telah dilaksanakan pelatihan GRC yang terencana"],
            ["id"=>105,"nomer"=>47,"nilai"=>0,"desc"=>"0 : belum ada audit GRC"],
            ["id"=>106,"nomer"=>47,"nilai"=>1,"desc"=>"1 : telah dilakukan audit GRC secara berkala"],
            ["id"=>107,"nomer"=>48,"nilai"=>0,"desc"=>"0 : belum ada tindak lanjut hasil audit GRC"],
            ["id"=>108,"nomer"=>48,"nilai"=>1,"desc"=>"1 : telah dilakukan tindak lanjut atas hasil audit GRC"],
            ["id"=>109,"nomer"=>49,"nilai"=>0,"desc"=>"0 : belum ada perencanaan keberlanjutan pelaksanaan GRC"],
            ["id"=>110,"nomer"=>49,"nilai"=>1,"desc"=>"1 : telah disusun rencana keberlanjutan pelaksanaan GRC"],
            ["id"=>111,"nomer"=>50,"nilai"=>0,"desc"=>"0 : belum ada komitmen pimpinan dalam implementasi GRC"],
            ["id"=>112,"nomer"=>50,"nilai"=>1,"desc"=>"1 : pimpinan menunjukkan komitmen dalam implementasi GRC"],
            ["id"=>113,"nomer"=>51,"nilai"=>0,"desc"=>"0 : belum ada sinergi antar unit kerja dalam pelaksanaan GRC"],
            ["id"=>114,"nomer"=>51,"nilai"=>1,"desc"=>"1 : telah terjalin sinergi antar unit kerja dalam pelaksanaan GRC"],
            ["id"=>115,"nomer"=>52,"nilai"=>0,"desc"=>"0 : belum ada dokumentasi pelaksanaan GRC"],
            ["id"=>116,"nomer"=>52,"nilai"=>1,"desc"=>"1 : telah dilakukan dokumentasi pelaksanaan GRC secara lengkap"],
            ["id"=>117,"nomer"=>53,"nilai"=>0,"desc"=>"0 : belum ada review berkala terhadap pelaksanaan GRC"],
            ["id"=>118,"nomer"=>53,"nilai"=>1,"desc"=>"1 : telah dilakukan review berkala terhadap pelaksanaan GRC"],
            ["id"=>119,"nomer"=>54,"nilai"=>0,"desc"=>"0 : belum ada pengintegrasian GRC dengan proses bisnis organisasi"],
            ["id"=>120,"nomer"=>54,"nilai"=>1,"desc"=>"1 : pelaksanaan GRC telah terintegrasi dengan proses bisnis organisasi"],
            ["id"=>121,"nomer"=>55,"nilai"=>0,"desc"=>"0 : belum ada koordinasi eksternal dalam pelaksanaan GRC"],
            ["id"=>122,"nomer"=>55,"nilai"=>1,"desc"=>"1 : telah dilakukan koordinasi eksternal dalam pelaksanaan GRC"],
            ["id"=>123,"nomer"=>56,"nilai"=>0,"desc"=>"0 : belum ada pengukuran efektivitas GRC"],
            ["id"=>124,"nomer"=>56,"nilai"=>1,"desc"=>"1 : telah dilakukan pengukuran efektivitas GRC dan digunakan sebagai dasar pengambilan keputusan"],
            ["id"=>125,"nomer"=>57,"nilai"=>0,"desc"=>"0 : belum ada mekanisme kontrol atas risiko baru yang muncul"],
            ["id"=>126,"nomer"=>57,"nilai"=>1,"desc"=>"1 : telah ada mekanisme kontrol untuk risiko baru yang muncul"],
            ["id"=>127,"nomer"=>58,"nilai"=>0,"desc"=>"0 : belum ada dukungan teknologi informasi terhadap pengendalian intern"],
            ["id"=>128,"nomer"=>58,"nilai"=>1,"desc"=>"1 : telah digunakan teknologi informasi dalam pengendalian intern"],
            ["id"=>129,"nomer"=>59,"nilai"=>0,"desc"=>"0 : belum ada pelibatan stakeholder dalam evaluasi GRC"],
            ["id"=>130,"nomer"=>59,"nilai"=>1,"desc"=>"1 : telah dilibatkan stakeholder dalam evaluasi pelaksanaan GRC"],
            ["id"=>131,"nomer"=>60,"nilai"=>0,"desc"=>"0 : belum ada indikator kinerja pengendalian intern"],
            ["id"=>132,"nomer"=>60,"nilai"=>1,"desc"=>"1 : telah ditetapkan indikator kinerja pengendalian intern"],
            ["id"=>133,"nomer"=>61,"nilai"=>0,"desc"=>"0 : belum ada pemantauan atas hasil pengendalian intern"],
            ["id"=>134,"nomer"=>61,"nilai"=>1,"desc"=>"1 : telah dilakukan pemantauan hasil pengendalian intern secara berkala"],
            ["id"=>135,"nomer"=>62,"nilai"=>0,"desc"=>"0 : belum ada pelatihan khusus terkait pengendalian intern"],
            ["id"=>136,"nomer"=>62,"nilai"=>1,"desc"=>"1 : telah dilakukan pelatihan khusus pengendalian intern"],
            ["id"=>137,"nomer"=>63,"nilai"=>0,"desc"=>"0 : belum ada review strategi GRC"],
            ["id"=>138,"nomer"=>63,"nilai"=>1,"desc"=>"1 : telah dilakukan review dan pembaruan strategi GRC"],
            ["id"=>139,"nomer"=>64,"nilai"=>1,"desc"=>"1 : organisasi telah memenuhi seluruh indikator implementasi GRC secara optimal"]
        ];
        $this->db->table('pilih_nilai')->insertBatch($data);
    }
}
