<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SatkerSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'id_satker' => 'fc4e4505-b83c-4b6d-8cbd-f007bb6d46a3',
                'kode_satker' => '024.12.632270',
                'nama_satker' => 'Poltekkes Kemenkes Mataram',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 1,
                'nama_kategori' => 'NON BLU',
                'pembina' => 'IR4',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'id_satker' => 'f3dc6006-4e80-410f-b1e8-787e49d1d461',
                'kode_satker' => '024.12.632348',
                'nama_satker' => 'Poltekkes Kemenkes Makassar',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 2,
                'nama_kategori' => 'BLU',
                'pembina' => 'IR4',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'id_satker' => 'f29e62d5-58ce-49fb-95cd-9daa4955123b',
                'kode_satker' => '024.12.632291',
                'nama_satker' => 'Poltekkes Kemenkes Pontianak',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 2,
                'nama_kategori' => 'BLU',
                'pembina' => 'IR4',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'id_satker' => 'f1abf40b-071c-4dea-9107-0f13abc41fd8',
                'kode_satker' => '024.12.637614',
                'nama_satker' => 'Poltekkes Kemenkes Ternate',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 1,
                'nama_kategori' => 'NON BLU',
                'pembina' => 'IR4',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'id_satker' => 'e9cd5f8d-f240-4144-b691-6bc859fffb2d',
                'kode_satker' => '024.12.637600',
                'nama_satker' => 'Poltekkes Kemenkes Maluku',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 1,
                'nama_kategori' => 'NON BLU',
                'pembina' => 'IR4',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),

            ],
            [
                'id' => 6,
                'id_satker' => 'e897d70c-63ac-4b24-ae28-2229f657a5f9',
                'kode_satker' => '024.12.632174',
                'nama_satker' => 'Poltekkes Kemenkes Tanjung Karang',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 2,
                'nama_kategori' => 'BLU',
                'pembina' => 'IR4',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),

            ],
            [
                'id' => 7,
                'id_satker' => 'e3b7c9c2-fc02-4c9e-8833-1ec2f846f442',
                'kode_satker' => '024.12.632132',
                'nama_satker' => 'Poltekkes Kemenkes Riau',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 1,
                'nama_kategori' => 'NON BLU',
                'pembina' => 'IR4',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),

            ],
            [
                'id' => 8,
                'id_satker' => 'e122f97c-6459-48ca-a9be-b827cfc19585',
                'kode_satker' => '024.12.632160',
                'nama_satker' => 'Poltekkes Kemenkes Palembang',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 1,
                'nama_kategori' => 'NON BLU',
                'pembina' => 'IR4',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),

            ],
            [
                'id' => 9,
                'id_satker' => 'de37ab7d-7082-47b6-bd93-17a0b1b52c3f',
                'kode_satker' => '024.12.637588',
                'nama_satker' => 'Poltekkes Kemenkes Surabaya',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 2,
                'nama_kategori' => 'BLU',
                'pembina' => 'IR4',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),

            ],
            [
                'id' => 10,
                'id_satker' => 'dcafcece-d3ca-44f6-87e7-1c9374ad26d0',
                'kode_satker' => '024.12.632128',
                'nama_satker' => 'Poltekkes Kemenkes Padang',
                'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
                'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
                'kategori' => 2,
                'nama_kategori' => 'BLU',
                'pembina' => 'IR4',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),

            ], 
            // [
            //     'id' => 11,
            //     'id_satker' => 'd7682a8d-3632-478a-8c05-49b042feb317',
            //     'kode_satker' => '024.12.637618',
            //     'nama_satker' => 'Poltekkes Kemenkes Mamuju',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 12,
            //     'id_satker' => 'd73bef89-d75f-4063-b17e-514613ae8889',
            //     'kode_satker' => '024.12.630877',
            //     'nama_satker' => 'Sekretariat Konsil Tenaga Kesehatan Indonesia',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 13,
            //     'id_satker' => 'd1c41a9a-f8d6-4919-9292-bb8896c8c0a1',
            //     'kode_satker' => '024.12.416242',
            //     'nama_satker' => 'Balai Pelatihan Kesehatan Cikarang',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 14,
            //     'id_satker' => 'cb14b55b-073f-455d-869e-383d6e89c369',
            //     'kode_satker' => '024.12.630876',
            //     'nama_satker' => 'Sekretariat Konsil Kedokteran Indonesia',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 15,
            //     'id_satker' => 'bfdb14cf-c1d2-47a8-ad1d-570b1af3abd5',
            //     'kode_satker' => '024.12.632217',
            //     'nama_satker' => 'Poltekkes Kemenkes Jakarta III',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 16,
            //     'id_satker' => 'bfbdc7ea-c133-4737-b7ff-cbf651a94013',
            //     'kode_satker' => '024.12.637617',
            //     'nama_satker' => 'Poltekkes Kemenkes Tanjungpinang',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 17,
            //     'id_satker' => 'bf0253a4-075a-4008-a7c2-d8ab288cc81c',
            //     'kode_satker' => '024.12.632181',
            //     'nama_satker' => 'Poltekkes Kemenkes Denpasar',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 18,
            //     'id_satker' => 'b96e60f3-2e4e-4eb7-bd45-dfa8f8b689a2',
            //     'kode_satker' => '024.12.416264',
            //     'nama_satker' => 'Balai Pelatihan Kesehatan Semarang',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 19,
            //     'id_satker' => 'b86e34c0-483a-4f87-be2c-196b7a6ac4fd',
            //     'kode_satker' => '024.12.637615',
            //     'nama_satker' => 'Poltekkes Kemenkes Banten',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 20,
            //     'id_satker' => 'af331a4c-a417-4b6d-9071-45eec6f4525e',
            //     'kode_satker' => '024.12.630875',
            //     'nama_satker' => 'Direktorat Pembinaan dan Pengawasan Tenaga Kesehatan',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],[
            //     'id' => 21,
            //     'id_satker' => 'fc4e4505-b83c-4b6d-8cbd-f007bb6d46a3',
            //     'kode_satker' => '024.12.632270',
            //     'nama_satker' => 'Poltekkes Kemenkes Mataram',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 22,
            //     'id_satker' => 'db8a1c4c-5c7f-4b68-9b79-9991118a2a50',
            //     'kode_satker' => '024.12.637511',
            //     'nama_satker' => 'Poltekkes Kemenkes Manado',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 23,
            //     'id_satker' => 'da77eb95-9fd4-4cc7-b265-c43dcf2022f1',
            //     'kode_satker' => '024.12.637509',
            //     'nama_satker' => 'Poltekkes Kemenkes Gorontalo',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 24,
            //     'id_satker' => 'd850a294-b5e6-44a5-8782-d5a63b0e471d',
            //     'kode_satker' => '024.12.632154',
            //     'nama_satker' => 'Poltekkes Kemenkes Banjarmasin',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 25,
            //     'id_satker' => 'd8385790-3a14-4d41-b3aa-d1cd8a2c5a35',
            //     'kode_satker' => '024.12.637608',
            //     'nama_satker' => 'Poltekkes Kemenkes Jayapura',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 26,
            //     'id_satker' => 'd6c1aa10-e49a-4066-b6be-79c38f0b194e',
            //     'kode_satker' => '024.12.416238',
            //     'nama_satker' => 'Balai Pelatihan Kesehatan Batam',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 27,
            //     'id_satker' => 'd5ec594b-866f-4f91-bfb5-5dc146540c27',
            //     'kode_satker' => '024.12.416240',
            //     'nama_satker' => 'Balai Pelatihan Kesehatan Jakarta',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 28,
            //     'id_satker' => 'd4a8f134-57d0-4693-bdb2-849f0ae9c260',
            //     'kode_satker' => '024.12.637620',
            //     'nama_satker' => 'Poltekkes Kemenkes Kupang',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 29,
            //     'id_satker' => 'd37708ce-4e1f-4438-9cc5-8fd6c392b8ff',
            //     'kode_satker' => '024.12.416241',
            //     'nama_satker' => 'Balai Pelatihan Kesehatan Makassar',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 30,
            //     'id_satker' => 'd2cbe9cf-8499-47c4-bb5d-748cdf9a88ff',
            //     'kode_satker' => '024.12.416239',
            //     'nama_satker' => 'Balai Pelatihan Kesehatan Tanjungkarang',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 31,
            //     'id_satker' => 'd1ebc75c-b5a0-4f3d-bdd5-77920d00cb6f',
            //     'kode_satker' => '024.12.416243',
            //     'nama_satker' => 'Balai Pelatihan Kesehatan Poltekkes Bandung',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 32,
            //     'id_satker' => 'd11a6d1b-f0c0-4f64-8a49-3cb748fc5b47',
            //     'kode_satker' => '024.12.637610',
            //     'nama_satker' => 'Poltekkes Kemenkes Yogyakarta',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 33,
            //     'id_satker' => 'cf53b55c-c67c-40ea-917e-f9ce140ba634',
            //     'kode_satker' => '024.12.632150',
            //     'nama_satker' => 'Poltekkes Kemenkes Semarang',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 34,
            //     'id_satker' => 'cd91a931-1836-4457-bc64-9306c813cb32',
            //     'kode_satker' => '024.12.416244',
            //     'nama_satker' => 'Balai Pelatihan Kesehatan Surabaya',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 1,
            //     'status_blu' => 'NON BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 35,
            //     'id_satker' => 'cb02ea03-5971-4388-8d4e-7ea4f5d53ed5',
            //     'kode_satker' => '024.12.637619',
            //     'nama_satker' => 'Poltekkes Kemenkes Banjarmasin 2',
            //     'organisasi_id' => '0d314d78-dd18-4310-afeb-40b8580fcbfc',
            //     'nama_organisasi' => 'Direktorat Jenderal Tenaga Kesehatan',
            //     'kategori' => 2,
            //     'status_blu' => 'BLU',
            //     'pembina' => 'IR4',
            //                     'created_at' => date('Y-m-d H:i:s'),
            //     'updated_at' => date('Y-m-d H:i:s'),
            // ],
            
            [
                'id' => 208,
                'id_satker' => 'a5f1d8e7-467f-4a1f-949d-619cd3083d75',
                'kode_satker' => '024.02.415366',
                'nama_satker' => 'Inspektorat Jenderal',
                'organisasi_id' => 'd80973d1-2873-4e10-a81c-0521c90c5cde',
                'nama_organisasi' => 'Inspektorat Jenderal',
                'kategori' => 1,
                'status_blu' => 'NON BLU',
                'pembina' => 'IR1',
                                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        
        $this->db->table('satker')->insertBatch($data);
    }
}
